### ISSUE TITLE
Update for media_player.tv fails (Home Assistant 2021.12.9 (Core))

### ISSUE THREAD

**Issue by JBakers** [jaruba/ha-samsungtv-tizen#169]
Since a few weeks I'm getting the following continious error in my logs.

Running Home Assistant 2021.12.9 (Core)

Error:
Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_tizen/smartthings.py:40
Integration: samsungtv_tizen (documentation)
First occurred: 20:57:10 (3 occurrences)
Last logged: 20:57:40

Update for media_player.tv fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 423, in update
    smartthings.device_update(self)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/smartthings.py", line 40, in device_update
    data = resp.json()
  File "/srv/homeassistant/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JBakers** [comment]
My fault, for some unknown reason the device ID in Smartthings changed.
