### ISSUE TITLE
SmartThings

### ISSUE THREAD

**Issue by Krocko** [jaruba/ha-samsungtv-tizen#21]
I have updated to the latest version and added the smarthings part to the config. 
Now I don’t see the selected source anymore and I get the following error:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 793, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 794, in <dictcomp>
    if getattr(self, attr) is not None
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 391, in source
    running_app = self._remote.get_running_app()
  File "/config/custom_components/samsungtv_tizen/remote.py", line 233, in get_running_app
    root = json.loads(data.encode('UTF-8'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Krocko** [comment]
After several restarts of home assistant the selected source is now visible. 
The `st_hdmi*` inputs are working, but the apps don’t. I can see the apps in the dropdown list and can select the apps, but the tv don‘t open the app. 
Also I get the following message in the home assistant log: `Received message for unregistered webhook xxxx-xxx......`

**Comment by Krocko** [comment]
Now the tv disappeared from homeassistant and I get the following error:
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 774, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 370, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 240, in _gen_installed_app_list
    app_list = self._remote.app_list()
  File "/config/custom_components/samsungtv_tizen/remote.py", line 179, in app_list
    self._ws_send(payload)
  File "/config/custom_components/samsungtv_tizen/remote.py", line 93, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_tizen/remote.py", line 108, in open
    sslopt=sslopt
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
socket.timeout: timed out
```

Sorry for spamming your repo, but I hope this logs are helpful.

**Comment by jaruba** [comment]
Set the `app_list` property in your config, as explained in the readme.

When opening an app, make sure to accept ALL the access request pop-ups on your TV, there can be many of then.

**Comment by Krocko** [comment]
Thank you. 
I used the autogenerated `app_list`, to test if the app input is working with this. 
Specified the `app_list` again and the error is gone. 
But the tv don‘t open the selected app. 
Will test this evening again.

**Comment by jaruba** [comment]
You haven't shown me your config yet, but in case it's correct, allow up to 24 hours for the custom component to settle down. Waiting this long has fixed many such issues due to the many access requests that this module creates.

**Comment by Krocko** [comment]
```
media_player:
  - platform: samsungtv_tizen
    host: 192.168.88.58
    port: 8002
    api_key: !secret samsungtv_tizen_api_key
    device_id: !secret samsungtv_tizen_device_id
    mac: !secret samsungtv_tizen_mac
    source_list: '{"TV": "ST_TV", "PlayStation 3": "ST_HDMI1", "Vu+ Ultimo 4K": "ST_HDMI2"}'
    app_list: '{"Prime Video": "3201512006785", "DS video": "111399002250", "YouTube": "111299001912", "TV DIGITAL": "y3opct3meL.TVDigital", "e-Manual": "20172100006", "Internet": "org.tizen.browser", "Netflix": "11101200001", "SmartIPTV": "g0ScrkpO1l.SmartIPTV", "TuneIn": "tisT7SVUug.tunein", "AccuWeather": "ABor2M9vjb.acc"}'
```
This is my config. 
I have now an other problem. 
If I turn off the tv, it is still displayed as on and the hole homeassistant gets unresponsive, till I turn on the tv again. 
This 100% reproduceable for me.

**Comment by Krocko** [comment]
Hi @jaruba have you any news or could you help me with the unresponsive homeassistant?

**Comment by jaruba** [comment]
I have been traveling for the last 7 days.

I'll try to look into it when I have some free time, an error log would of definitely helped too..

**Comment by Krocko** [comment]
Sorry @jaruba. I don’t want to annoying you. 
There are no errors in the log.
I removed the SmartThings part from the config and added the ping method. This is working really good. 
So could you make it possible to use SmartThings for the input and source states and ping for the on/off state?

**Comment by jaruba** [comment]
@Krocko I am not annoyed, sorry if it came out like that, I should use more emojis.

I suspected the SmartThings "turn off" method being the cause of this, there have been some other issues with it too. I will remove the "turn off" feature from SmartThings, I think some older TVs don't support it at all anyway.

**Comment by Krocko** [comment]
All good @jaruba. 
Thank you for working on this.

**Comment by jaruba** [comment]
@Krocko Latest version uses the "ping" method by default, "smartthings" has been added as an alternative update method if someone wants to select it. The turn off feature has been reverted to not use the SmartThings method for this.

**Comment by Krocko** [comment]
Thank you very much @jaruba. 
All is working.
