### ISSUE TITLE
Some Google Assistant audio commands not working

### ISSUE THREAD

**Issue by nmajin** [jaruba/ha-samsungtv-tizen#23]
I have a `2016 Samsung 6 Series (55) UN55KU6290` TV and all functionality of this component (latest version from HACS (1.4.0)) for the volume works fine (mute, up, down) in the HA UI, but no audio commands work in Google Assistant. I can confirm I get some functionality with the voice commands,  like changing the source to particular apps, but audio commands do not work (nothing happens, and then error for volume down):

Mute
```
2020-02-23 18:26:20 INFO (SyncWorker_5) [root] Sending key KEY
```

Volume Up
```
2020-02-23 18:25:04 INFO (SyncWorker_0) [root] Sending key KEY
```

Volume Down
```
2020-02-23 18:25:15 INFO (SyncWorker_7) [root] Sending key KEY
2020-02-23 18:25:16 ERROR (MainThread) [homeassistant.components.google_assistant.smart_home] Unexpected error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 57, in _process
    result = await handler(hass, data, inputs[0].get("payload"))
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 176, in handle_devices_execute
    await entities[entity_id].execute(data, execution)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 488, in execute
    await trt.execute(command, data, params, challenge)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 1428, in execute
    await self._execute_volume_relative(data, params)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 1420, in _execute_volume_relative
    context=data.context,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1204, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value must be at least 0 for dictionary value @ data['volume_level']
2020-02-23 18:25:16 ERROR (MainThread) [homeassistant.components.google_assistant.smart_home] Error handling message {'inputs': [{'context': {'locale_country': 'US', 'locale_language': 'en'}, 'intent': 'action.devices.EXECUTE', 'payload': {'commands': [{'devices': [{'id': 'media_player.living_room_tv'}], 'execution': [{'command': 'action.devices.commands.volumeRelative', 'params': {'relativeSteps': -1, 'volumeRelativeLevel': -1}}]}]}}], 'requestId': '7397537694740777833'}: {'errorCode': 'unknownError'}
```

**Comment by jaruba** [comment]
Works fine here, and those errors don't make much sense. Try saying "ok google, sync my devices" and try the commands again. If it still does not work, try doing it again (syncing devices).

I can't explain it tbh, but sometimes when syncing devices some features of the devices are not synced correctly. This seems to be either a HA or Google Home issue.

Tell me the results of syncing and retrying a couple of times.

**Comment by nmajin** [comment]
Yep, no luck on syncing the devices. I get the same as noted above: Mute/Volume UP does nothing and Volume Down throws the exception. This is only if I use Google Assistant, UI works fine.

**Comment by jaruba** [comment]
TBH, I think the Google Assistant integration or HA is broken in your case. Try updating both?

Because this:
```
2020-02-23 18:25:04 INFO (SyncWorker_0) [root] Sending key KEY
```

Is used to get the On / Off state of the TV, it's supposed to be there. You can make it go away by setting `update_method: "ping"`.

And the error you're getting, if you go through it's thread, it says absolutely nothing about `ha-samsungtv-tizen` in there, so your commands don't even get to the component.

Again, try updating both, and sync your devices.

**Comment by jaruba** [comment]
@nmajin Any luck with this? Did you try updating HA as I suggested?

**Comment by nmajin** [comment]
> @nmajin Any luck with this? Did you try updating HA as I suggested?

No luck, I've also updated to your latest integration in HACS. I also tried setting `update_method: "ping"`, which stopped the "Sending key KEY" messages coming through to use ping instead for device connection status.

Here are the HA logs when using the component via the UI:
```
2020-03-02 20:20:01 INFO (SyncWorker_3) [root] Sending key KEY_MUTE
2020-03-02 20:20:05 INFO (SyncWorker_8) [root] Sending key KEY_VOLDOWN
2020-03-02 20:20:05 INFO (SyncWorker_8) [root] Sending key KEY_VOLDOWN
2020-03-02 20:20:08 INFO (SyncWorker_5) [root] Sending key KEY_VOLUP
2020-03-02 20:20:13 INFO (SyncWorker_8) [root] Sending run app app_id: 3201512006963 app_type: DEEP_LINK meta_tag: 
2020-03-02 20:20:21 INFO (SyncWorker_4) [root] Sending key KEY_MUTE
2020-03-02 20:20:23 INFO (SyncWorker_10) [root] Sending key KEY_MUTE
```

And here they are using Google Assistant (notice that the source actually works, but nothing with volume (still get an exception when calling "volume down"):
```
2020-03-02 20:20:57 INFO (SyncWorker_17) [root] Sending run app app_id: 3201512006963 app_type: DEEP_LINK meta_tag: 
2020-03-02 20:21:17 ERROR (MainThread) [homeassistant.components.google_assistant.smart_home] Unexpected error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 57, in _process
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
2020-03-02 20:21:17 ERROR (MainThread) [homeassistant.components.google_assistant.smart_home] Error handling message {'inputs': [{'context': {'locale_country': 'US', 'locale_language': 'en'}, 'intent': 'action.devices.EXECUTE', 'payload': {'commands': [{'devices': [{'id': 'media_player.living_room_tv'}], 'execution': [{'command': 'action.devices.commands.volumeRelative', 'params': {'relativeSteps': -1, 'volumeRelativeLevel': -1}}]}]}}], 'requestId': '13619454378009181731'}: {'errorCode': 'unknownError'}
2020-03-02 20:21:48 INFO (SyncWorker_8) [root] Sending run app app_id: 3201512006963 app_type: DEEP_LINK meta_tag: 
2020-03-02 20:21:48 INFO (SyncWorker_8) [root] Sending run app app_id: 3201512006963 app_type: DEEP_LINK meta_tag: 
```

**Comment by jaruba** [comment]
Yeah, you're still getting an error in `smart_home.py` which is a part of `google_assistant`, your voice command never reaches the Samsung TV component at all. So nothing changed..

**Comment by jaruba** [comment]
Why do you need vol up / down though? Those commands do +-1 / 100 which makes them quite useless.

Does changing volume level work?

> Set volume to 50 on SAMSUNG-TV-NAME-HERE (sets volume to 50 out of 100)

**Comment by nmajin** [comment]
> Why do you need vol up / down though? Those commands do +-1 / 100 which makes them quite useless.
> 
> Does changing volume level work?
> 
> > Set volume to 50 on SAMSUNG-TV-NAME-HERE (sets volume to 50 out of 100)

Nope, nothing at all with volume works via the voice commands...where in your code are you doing this?

**Comment by jaruba** [comment]
The difference between supporting voice commands and not supporting them are these lines:
- https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L24
- https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L460-L463

Which declare that the TV is of `DEVICE_CLASS_TV`.

Then the volume related methods are used normally for both the UI and the voice commands:
- https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L499-L513

For me all the volume voice commands work perfectly on HA 0.105.2.

**Comment by nmajin** [comment]
Yea, my device is of type "tv" so no issue there. Even shows up as a TV in Google Home. How does your code technically communicate with Google on say sending the `KEY_MUTE`?

- https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/media_player.py#L507

Google Assistant actually respond with "OK" when I say "Mute Living Room TV" but nothing happens.

How could some voice commands work but not others? For example, all of these work:
- TV on
- TV off
- Change source

-

**Comment by jaruba** [comment]
> How does your code technically communicate with Google on say sending KEY_MUTE?

My component doesn't communicate with Google at all. Google communicates with HA, and then HA runs commands from my component. But for the sake of discussion, I'll tell you what commands HA triggers in my component based on voice commands.

- 'mute' - runs `set_volume_level(0)` (yes, it does not use the `mute_volume()` method for some reason)
- `unmute` - runs `set_volume_level(X)` (where X is the previous volume level before muting)
-  'set volume to X%` - runs `set_volume_level(X)`
-  'volume up' - runs `volume_up()` (i'm presuming this is the method used here..)
- `volume down` - runs `volume_down()` (i'm presuming this is the method used here..)

> I am on HA 0.106.5, but I've tried all versions of 0.105.

Then maybe the issue is not in HA, maybe u have different Google devices then I do, and your devices are running a different assistant version that is no longer fully compatible with HA. The assistant version on your devices might even be relative to regional data.

**Comment by nmajin** [comment]
> Then maybe the issue is not in HA, maybe u have different Google devices then I do, and your devices are running a different assistant version that is no longer fully compatible with HA. The assistant version on your devices might even be relative to regional data.

Thanks for the info. I have the 1st gen Google Home minis and I've been also testing Google Assistant via the Google Home iOS app and the actual Google Assistant iOS app, they all behave the same.

**Comment by jaruba** [comment]
I'll close this due to inactivity, and the fact that nobody else ever encountered this issue.

If there are more users that have this problem we can reopen it, but currently it seems like a very isolated case.
