### ISSUE TITLE
entity not available

### ISSUE THREAD

**Issue by Stooovie** [jaruba/ha-samsungtv-tizen#29]
I'm getting this:

`Update for media_player.customtv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 320, in update
    smartthings.device_update(self)
  File "/config/custom_components/samsungtv_tizen/smartthings.py", line 40, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

HA 106.3 on Rpi4, Samsung NU8000. It sporadically works but most times I'm getting this error. IP, MAC, Device_id and api_key are correct.

**Comment by jaruba** [comment]
> IP, MAC, Device_id and api_key are correct.

No, that error means that ur api_key and/or device_id is NOT CORRECT.

Many here make the mistake of using the Network Device ID instead of the actual Device ID.

**Comment by Stooovie** [comment]
You're correct, I had the Network Device ID in config.yaml instead of Device ID.

BUT, it's super weird because with the wrong device_ID, I did get a list of apps in Source (when the integration worked at all). Now with correct ID, I only get TV and HDMI. Everything is restarted, new token was generated.

**Comment by jaruba** [comment]
The `app_list` has nothing to do with the SmartThings features. Never rely on the autogenerated `app_list`, for one, it cannot be extracted from a TV that is turned off.

Always set the `app_list` manually in ur config for best performance.

**Comment by jaruba** [comment]
Also, now that u have SmartThings enabled, use the ST_TV, ST_HDMI1, ST_HDMI2, ST_HDMI3, etc in your `source_list` to efficiently set input sources.

**Comment by Stooovie** [comment]
The entity doesn't get created with this in config.yaml:

`source_list: '{"Kodi": "ST_HDMI2", "PC": "ST_HDMI3", "Playstation": "ST_HDMI1}'`

It gives this error:
`Error while setting up samsungtv_tizen platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 157, in setup_platform
    add_entities([SamsungTVDevice(host, port, name, timeout, mac, uuid, update_method, update_custom_ping_url, source_list, app_list, api_key, device_id, show_channel_number, broadcast)])
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 181, in __init__
    self._source_list = json.loads(source_list)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 55 (char 54)`

Manually added Apps list works fine.

**Comment by jaruba** [comment]
i guess we can close this ticket now

**Comment by Stooovie** [comment]
Fully working! Thanks for your help!
