### ISSUE TITLE
Tv's not switching on and HA log

### ISSUE THREAD

**Issue by jackkitley** [jaruba/ha-samsungtv-tizen#34]
**Setup**
```
- platform: samsungtv_tizen
  name: Bedroom TV
  host: 192.168.88.72
  broadcast_address: 192.168.88.72 **<--- Not sure if this is needed**
  port: 8002
  api_key: "<token>"
  device_id: "<token>"
  show_channel_number: true
```

Logger: homeassistant.core
First occured: 4:17:06 PM (4 occurences)
Last logged: 4:17:27 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 774, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 446, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 301, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 237, in app_list
    'to': 'host'
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 149, in open
    sslopt=sslopt
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
socket.timeout: timed out

**Comment by jaruba** [comment]
Set `app_list` manually in your config as explained in this component's README:
https://github.com/jaruba/ha-samsungtv-tizen/blob/master/README.md

And remove the `broadcast_address` that is only needed if your TVs are on a different subnet then your HA server.

**Comment by jackkitley** [comment]
```
Log Details (ERROR)
Logger: custom_components.xboxone.media_player
First occured: 5:55:25 PM (1 occurences)
Last logged: 5:55:25 PM

Unreachable /poweron endpoint
```

**Comment by jackkitley** [comment]
Got that now. I can turn the tv off but not on again

**Comment by jaruba** [comment]
What's `custom_components.xboxone.media_player` from your error?

Anyway, you need to set `mac` too if you want ur TVs to be started through WOL.

**Comment by jackkitley** [comment]
@jaruba Thanks. Ive added my mac address for wired connection and i added the wake_on_lan package.

I get this error when using no port:

```Logger: homeassistant.components.websocket_api.http.connection.2930875120
Integration: websocket_api (documentation, issues)
First occured: 9:00:29 PM (9 occurences)
Last logged: 9:01:05 PM

{'event': 'ms.channel.unauthorized'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 527, in async_turn_off
    await self.hass.async_add_job(self.turn_off)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 499, in turn_off
    self.send_command("KEY_POWER")
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 373, in send_command
    self._ws.send_key(payload, key_press_delay)
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 181, in send_key
    key_press_delay
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 160, in open
    raise exceptions.ConnectionFailure(response)
custom_components.samsungtv_tizen.exceptions.ConnectionFailure: {'event': 'ms.channel.unauthorized'}
Failed to call service media_player/turn_off. {'event': 'ms.channel.unauthorized'}
```

**Comment by jackkitley** [comment]
Also this error was logged: 


```
Logger: homeassistant.core
First occured: 8:58:57 PM (2 occurences)
Last logged: 8:59:14 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 774, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 446, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 301, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 237, in app_list
    'to': 'host'
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 149, in open
    sslopt=sslopt
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
socket.timeout: timed out
```

**Comment by jackkitley** [comment]
> What's `custom_components.xboxone.media_player` from your error?
> 
> Anyway, you need to set `mac` too if you want ur TVs to be started through WOL.

I added the correct mac address. If i turn on the tv power button on HA once then it doesnt work. If i click it multiple times quickly then it turns on.

Ive i use the service i also have to click it multiple times, it doesnt work on first click.

**Comment by jaruba** [comment]
I don't think there's anything I can do about needing to press 2 times for it to turn on. The WOL signal is sent every time u press the button, the TV just doesn't want to respond acordingly.

One of the errors u posted says u didn't set `app_list` like I told u to.

**Comment by jackkitley** [comment]
I added the app_list:

```
- platform: samsungtv_tizen
  name: Living Room TV
  host: 192.168.88.71
  port: 8002
  update_method: "smartthings"
  mac: "d0:d0:03:04:eb:84"
  api_key: "<token>"
  device_id: "<token>"
  app_list: '{"YouTube": "111299001912"}'
```

**Comment by jaruba** [comment]
remove `update_method: "smartthings"`, the default update method is the best imo.

Your error from:
```
First occured: 8:58:57 PM (2 occurences)
Last logged: 8:59:14 PM
```

has `self._gen_installed_app_list()` in it's thread, that method is only used if you do not set an `app_list`, so maybe u got the error before setting it.

Anyway, it sounds like the component works for you now, at least as much as it works for the rest of the users. Can we close this issue?

**Comment by jackkitley** [comment]
@jaruba Yes, all works except websockets and it takes about 20 seconds to ping if the state is on of off .

**Comment by jaruba** [comment]
Please test the latest release: v1.5.0

If you still have the same issues you can reopen the ticket.
