### ISSUE TITLE
It works, but in the error log

### ISSUE THREAD

**Issue by poisondima** [jaruba/ha-samsungtv-tizen#43]
Thank you for your work. I used "roberodin / ha-samsungtv-custom" and now decided to try your component. Of the pluses, I noticed more quickly the determination that the TV was turned off. Also was able to add USB to source_list.
My configuration "Samsung 5 Series UE32M5500 (2017)", HA v107.4:
- platform: samsungtv_tizen
    host: 192.168.8.6
    port: 8002
    mac: <***hide***>
    source_list: '{"TV": "KEY_TV", "HDMI": "KEY_HDMI", "USB": "KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER"}'

Visually, everything works, but there are the following errors in the log, how can I remove them?
```
2020-03-21 17:13:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 781, in capability_attributes
    source_list = self.source_list
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 532, in source_list
    self._gen_installed_app_list()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 337, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 237, in app_list
    'to': 'host'
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 149, in open
    sslopt=sslopt
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
socket.timeout: timed out
```
and next
```
2020-03-21 17:14:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 781, in capability_attributes
    source_list = self.source_list
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 532, in source_list
    self._gen_installed_app_list()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 337, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 237, in app_list
    'to': 'host'
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 149, in open
    sslopt=sslopt
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 189, in _open_socket
    raise error
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 172, in _open_socket
    sock.connect(address)
OSError: [Errno 113] No route to host
```

**Comment by jaruba** [comment]
Set `app_list` manually as described in the readme

**Comment by poisondima** [comment]
Thank you, there are no more errors.
I did not think that "app_list" is a required parameter.

**Comment by jaruba** [comment]
it's not, as long as u don't mind the errors in case it fails getting them automatically
