### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by klatvo** [jaruba/ha-samsungtv-tizen#44]
**Installation worked fine. HA media player is here, but protocoll + error in log:**

Protokolldetails ( WARNING ) 
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:284 
First occurred: 17:15:45 (1 occurrences) 
Last logged: 17:15:45 
Updating state for media_player.tv_eg_2 (<class 'custom_components.samsungtv_tizen.media_player.SamsungTVDevice'>) took 0.575 seconds. **Please report it to the custom component author.**

**Logger: homeassistant.core**
Source: custom_components/samsungtv_tizen/websockets.py:241 
First occurred: 17:15:33 (1 occurrences) 
Last logged: 17:15:33 
Error doing job: Task exception was never retrieved 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
  File "/usr/local/lib/python3.7/ssl.py", line 1056, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.7/ssl.py", line 931, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 781, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 532, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 337, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 241, in app_list
    response = self._process_api_response(self.connection.recv())
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: The read operation timed out

**Comment by jaruba** [comment]
looks like this: https://github.com/jaruba/ha-samsungtv-tizen/issues/43

**Comment by jaruba** [comment]
i presume the ticket i mentioned fixed your issue? given the lack of response i will close this ticket, if you consider it's still an issue you can reopen it.
