### ISSUE TITLE
Broken pipe on UE55NU8042

### ISSUE THREAD

**Issue by sstefanowski** [jaruba/ha-samsungtv-tizen#51]
Hello,

I have a TV as in the subject above. I set up this great Tizen component today  (HA 0.107 and Tizen 1.4.6) - with SmartThings API configured, but without custom App list yet.

Now, after setup and HA restart I managed successfully open the browser on TV calling service media_player.play_media from HA as described in the docs, but.... it was successful JUST ONCE. Any subsequent attempts are giving the Broken pipe error as below:

Any hits?

``
Apr 04 03:37:18 hassbian hass[32378]: 2020-04-04 03:37:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1563468176] [Errno 32] Broken pipe
Apr 04 03:37:18 hassbian hass[32378]: Traceback (most recent call last):
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
Apr 04 03:37:18 hassbian hass[32378]:     connection.context(msg),
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1234, in async_call
Apr 04 03:37:18 hassbian hass[32378]:     await asyncio.shield(self._execute_service(handler, service_call))
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1257, in _execute_service
Apr 04 03:37:18 hassbian hass[32378]:     await handler.func(service_call)
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 198, in handle_service
Apr 04 03:37:18 hassbian hass[32378]:     self._platforms.values(), func, call, required_features
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 402, in entity_service_call
Apr 04 03:37:18 hassbian hass[32378]:     future.result()  # pop exception if have
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 599, in async_request_call
Apr 04 03:37:18 hassbian hass[32378]:     await coro
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 433, in _handle_entity_call
Apr 04 03:37:18 hassbian hass[32378]:     await result
Apr 04 03:37:18 hassbian hass[32378]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/media_player.py", line 704, in async_play_media
Apr 04 03:37:18 hassbian hass[32378]:     self._ws.open_browser(media_id)
Apr 04 03:37:18 hassbian hass[32378]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 228, in open_browser
Apr 04 03:37:18 hassbian hass[32378]:     url
Apr 04 03:37:18 hassbian hass[32378]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 218, in run_app
Apr 04 03:37:18 hassbian hass[32378]:     'metaTag': meta_tag
Apr 04 03:37:18 hassbian hass[32378]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_tizen/websockets.py", line 112, in _ws_send
Apr 04 03:37:18 hassbian hass[32378]:     self.connection.send(payload)
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
Apr 04 03:37:18 hassbian hass[32378]:     return self.send_frame(frame)
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
Apr 04 03:37:18 hassbian hass[32378]:     l = self._send(data)
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
Apr 04 03:37:18 hassbian hass[32378]:     return send(self.sock, data)
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
Apr 04 03:37:18 hassbian hass[32378]:     return _send()
Apr 04 03:37:18 hassbian hass[32378]:   File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
Apr 04 03:37:18 hassbian hass[32378]:     return sock.send(data)
Apr 04 03:37:18 hassbian hass[32378]:   File "/usr/local/lib/python3.7/ssl.py", line 984, in send
Apr 04 03:37:18 hassbian hass[32378]:     return self._sslobj.write(data)
Apr 04 03:37:18 hassbian hass[32378]: BrokenPipeError: [Errno 32] Broken pipe
``

**Comment by jaruba** [comment]
Try disabling HA's default component for samsung TVs

**Comment by jaruba** [comment]
Sorry for being inactive lately. I've made an announcement [here](https://community.home-assistant.io/t/improving-samsung-tv-control/151922/230?u=jaruba).
