### ISSUE TITLE
After upgrading crash all media_player integration

### ISSUE THREAD

**Issue by naked-head** [jaruba/ha-samsungtv-tizen#58]
My installation is on a Raspberry pi 3B using python virtual environment, no hass.io installation.
After upgrading to last version (0.108.5 and today with 0.108.6 too) no media_player entity work. This is log output section:

> 2020-04-17 15:46:08 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration media_player - received exception
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 763, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 44, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 50, in async_setup_component
    return await task  # type: ignore
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
    hass, config, integration
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 763, in async_process_component_config
    p_integration = await async_get_integration_with_requirements(hass, p_name)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/requirements.py", line 55, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/requirements.py", line 99, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/srv/homeassistant/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3078, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/srv/homeassistant/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/srv/homeassistant/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/srv/homeassistant/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object 

> 

and this is my config line in configuration.yaml:

`- platform: samsungtv_tizen
    host: 192.168.0.101
    port: 8002
    name: Samsung Q70Q65
    mac: 00:c3:f4:90:1a:e8
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
    device_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    app_list: '{"Netflix":"11101200001", "YouTube":"111299001912", "Prime Video":"3201512006785", "Plex":"3201512006963", "Spotify":"3201606009684"}'
    source_list: '{"TV":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_ENTER","Chromecast":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER","Manual":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER"}'`

if I comment out all row in configuration.yaml the error disappear and the media_player entity return usable. 
Before this update the TV not work very well because I spend just some minute on setting it, but now is completely unusable.

**Comment by jaruba** [comment]
Sorry for being inactive lately. I've made an announcement [here](https://community.home-assistant.io/t/improving-samsung-tv-control/151922/230?u=jaruba).
