### ISSUE TITLE
HA error in logs

### ISSUE THREAD

**Issue by wochen** [jaruba/ha-samsungtv-tizen#6]
Hi,

I've successfully installed plugin, but I'm getting some errors in logs, see below:

> 2020-01-05 21:33:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/config/custom_components/samsungtv_custom/media_player.py", line 319, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_custom/media_player.py", line 229, in _gen_installed_app_list
    app_list = self._remote.app_list()
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 179, in app_list
    self._ws_send(payload)
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 93, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_custom/samsungtvws/remote.py", line 108, in open
    sslopt=sslopt
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 511, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 186, in _open_socket
    raise error
  File "/usr/local/lib/python3.7/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
OSError: [Errno 113] Host is unreachable

Any ideas?

**Comment by jaruba** [comment]
Wrong TV IP? Or incompatible Samsung TV?

**Comment by wochen** [comment]
Hi @jaruba ,

the IP address is set correctly and the navigation works fine in HA. Even turning the TV on (Ethernet link) works really nice.

Only these logs are annoying ;)

My TV model: UE55RU8002U

**Comment by jaruba** [comment]
@wochen I'm not sure why the WS server is unreachable in your case.. can you show me your config? It might be set to the wrong port. (it's usually `8001` or `8002`)

You can also avoid this error that seems to happen when getting the `app_list`, so you can also probably avoid it by setting the `app_list` to a custom value yourself in the config.

**Comment by wochen** [comment]
@jaruba thanks for your reply. 

Here is my current configuration:
`media_player:
  - platform: samsungtv_custom
    host: 192.168.5.25
    port: 8002
    mac: "00:11:22:33:44:55"`

re: `app_list` - should I set this to just one app? Or for all of apps I'm using?

**Comment by jaruba** [comment]
whichever apps u normally use

**Comment by wochen** [comment]
@jaruba 
thanks!
applied and there is only one warning now:
`2020-01-10 12:57:13 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for media_player.samsung_tv_remote (<class 'custom_components.samsungtv_custom.media_player.SamsungTVDevice'>) took 3.185 seconds. Please report platform to the developers at https://goo.gl/Nvioub`

**Comment by jaruba** [comment]
yeah, that's unfortunately a common warning with this component

**Comment by jaruba** [comment]
I think this was fixed with the newer releases, I'll close this issue for now.

If you still have issues, I can reopen it.
