### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by andrea-mattioli** [jaruba/ha-samsungtv-tizen#63]
Hi this is my configuration for tv model UE55RU7450UXZT:
```
  - platform: samsungtv_tizen
    name: tv_camera_matrimoniale
    host: 192.168.1.52
    mac: "00:c3:f4:e0:81:74"
    port: 8002
    api_key: *****************************  
    device_id: ******************************
```
i can manage turn_on - turn_off source, volume etc.. but when i call service:
```
media_player.play_media
{
  "entity_id": "media_player.tv_camera_matrimoniale",
  "media_content_type": "browser",
  "media_content_id": "https://www.google.com",
}
```
I receive errno 32 Broken pipe:

[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1247, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1282, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 704, in async_play_media
    self._ws.open_browser(media_id)
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 228, in open_browser
    url
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 218, in run_app
    'metaTag': meta_tag
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 112, in _ws_send
    self.connection.send(payload)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jaruba** [comment]
Sorry for being inactive lately. I've made an announcement [here](https://community.home-assistant.io/t/improving-samsung-tv-control/151922/230?u=jaruba).

**Comment by jaruba** [comment]
This is an old issue, please test the latest release: v1.5.0

If you still have the same problems you can reopen the ticket.
