### ISSUE TITLE
integration has stopped working

### ISSUE THREAD

**Issue by FilippoS1973** [jaruba/ha-samsungtv-tizen#65]
TV Model Samsung QE75Q7FN
this is my confguration:

platform: samsungtv_tizen
name: Samsung TV Q75
host: samsungTV_ip
port: 8002
mac: samsungTV_MAC
api_key: "my_API_KEY"
device_id: "MY_DEVICE_ID"
source_list: '{"TV": "ST_TV", "1": "ST_HDMI1", "Decoder 1": "ST_HDMI3", "LG Blu-Ray": "ST_HDMI4"}'
update_method: "smartthings"

(ERROR)
Logger: homeassistant.core
Source: custom_components/samsungtv_tizen/websockets.py:152
First occurred: 0:52:06 (1 occurrences)
Last logged: 0:52:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
  File "/usr/local/lib/python3.7/ssl.py", line 1056, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.7/ssl.py", line 931, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 784, in capability_attributes
    source_list = self.source_list
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 532, in source_list
    self._gen_installed_app_list()
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 337, in _gen_installed_app_list
    app_list = self._ws.app_list()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 237, in app_list
    'to': 'host'
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 109, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_tizen/websockets.py", line 152, in open
    response = self._process_api_response(self.connection.recv())
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: The read operation timed out

**Comment by FilippoS1973** [comment]
I uninstalled and reinstalled. back to work.
