### ISSUE TITLE
python3.8 websocket timeout

### ISSUE THREAD

**Issue by terminet85** [jaruba/ha-samsungtv-tizen#7]
2020-01-06 14:56:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/components/media_player/__init__.py", line 794, in state_attributes
    state_attr = {
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/media_player.py", line 319, in source_list
    self._gen_installed_app_list()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/media_player.py", line 229, in _gen_installed_app_list
    app_list = self._remote.app_list()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 179, in app_list
    self._ws_send(payload)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 93, in _ws_send
    self.open()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 111, in open
    response = json.loads(self.connection.recv())
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 314, in recv
    opcode, data = self.recv_data()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 331, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 344, in recv_data_frame
    frame = self.recv_frame()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 378, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_core.py", line 453, in _recv
    return recv(self.sock, bufsize)
  File "/home/homeassistant/.pyenv/versions/3.8.0/lib/python3.8/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: The read operation timed out

**Comment by jaruba** [comment]
What TV product code? Does it use Tizen? What is the fabrication date?

**Comment by jaruba** [comment]
Also mention Tizen version, pls.

**Comment by terminet85** [comment]
There is a bug in the last websocket-client module.

https://github.com/websocket-client/websocket-client/issues/595

**Comment by jaruba** [comment]
Well, shit :)

**Comment by jaruba** [comment]
I think this was fixed with the newer releases, I'll close this issue for now.

If you still have issues, I can reopen it.
