### ISSUE TITLE
Error when turning tv off

### ISSUE THREAD

**Issue by jackkitley** [jaruba/ha-samsungtv-tizen#74]
Getting this error with turning off tv:

Home Assistant Core 0.110.7

My configs:
```
- platform: samsungtv_tizen
  name: Main TV
  host: 192.168.88.71
  port: 8002
  update_method: "smartthings"
  mac: "d0:d0:03:04:eb:84"
  api_key: "<key>"
  device_id: "<id>"
  source_list: '{"TV": "KEY_TV", "Apple Tv": "ST_HDMI1", "Xbox": "ST_HDMI2"}'
  app_list: '{"YouTube": "111299001912"}'
  
- platform: samsungtv_tizen
  name: Bedroom TV
  host: 192.168.88.72
  port: 8002
  mac: "00:7c:2d:d0:3e:e7"
  api_key: "<key>"
  device_id: "<id>"
  source_list: '{"TV": "KEY_TV", "HDMI 1": "ST_HDMI1", "HDMI 2": "ST_HDMI2"}'
  app_list: '{"Youtube Kids": "5SLwh7m3En.TizenYouTubeKids","RedBull TV": "4OAwqypfRT.RedBullTV","Showmax": "Nm4zJjYmVG.Shomwax","DSTV Now": "CXNLCPYe82.Dstvnow","Emby": "vYmY3ACVaa.emby","Netflix": "11101200001", "YouTube": "111299001912"}'

```

Logger: homeassistant.components.websocket_api.http.connection.2852310352
Source: custom_components/samsungtv_tizen/media_player.py:599
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:29:26 AM (3 occurrences)
Last logged: 8:29:36 AM

'SamsungTVDevice' object has no attribute '_auto_gen_installed_app_list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 530, in async_turn_off
    await self.hass.async_add_job(self.turn_off)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 599, in turn_off
    if self._auto_gen_installed_app_list == True:
AttributeError: 'SamsungTVDevice' object has no attribute '_auto_gen_installed_app_list'

**Comment by jaruba** [comment]
set `app_list` manually as described in the readme

**Comment by jackkitley** [comment]
@jaruba As in my example configs above?

**Comment by jaruba** [comment]
oh, i see the issue now, the code will need to be fixed regarding this, thanks for reporting

**Comment by jaruba** [comment]
I've made a new release, it's best to uninstall the old version and install the new one to avoid issues.
