### ISSUE TITLE
Source not changing to apps

### ISSUE THREAD

**Issue by fellipeisensee** [jaruba/ha-samsungtv-tizen#78]
Thanks for this custom component, it’s really great to have my tv on HA. 

Unfortunately, I'm having an issue when trying to change source an app. It does map all aps as sources, but when I try to select one of them, it does not change on TV. If I change to an app on TV, it updates the source status on HA.

Changing to HDMI sources through smarthings keys are working, I’m only having problems with apps.

![image](https://user-images.githubusercontent.com/62270932/86469265-6a12d680-bd0f-11ea-96e3-1c359a94978f.png)

My configuration.yaml is like this. I already tried  changing update_method: and app_list: but the issue persists.

media_player:
  - platform: samsungtv_tizen
    name: Samsung Q80
    host: #########
    port: 8002
    mac: #########
    update_method: smartthings
    source_list: '{"TV": "KEY_TV", "HDMI1": "ST_HDMI1", "HDMI2": "ST_HDMI2", "HDMI3": "ST_HDMI3", "HDMI4": "ST_HDMI4"}'
    api_key: "#############################"
    device_id: "#############################"

Logs:

Translation Error: The intl string context variable "Level" was not provided to the string "Detalhes do log ({Level})"
Logger: homeassistant.components.websocket_api.http.connection.1848895248
Source: custom_components/samsungtv_tizen/smartthings.py:38
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:17:39 (1 occurrences)
Last logged: 9:17:39

HTTPSConnectionPool(host='api.smartthings.com', port=443): Max retries exceeded with url: /v1/devices/2afd9022-b0c1-4ab0-be32-fd2c72870eb4/commands (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x68b02310>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x68b02310>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.smartthings.com', port=443): Max retries exceeded with url: /v1/devices/2afd9022-b0c1-4ab0-be32-fd2c72870eb4/commands (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x68b02310>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 744, in async_select_source
    await self.hass.async_add_job(self.send_command, self._source_list[ source ])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 468, in send_command
    self.update(no_throttle=True)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 421, in update
    smartthings.device_update(self)
  File "/config/custom_components/samsungtv_tizen/smartthings.py", line 38, in device_update
    cmdurl = requests.post(API_COMMAND,data=COMMAND_REFRESH ,headers=REQUEST_HEADERS)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.smartthings.com', port=443): Max retries exceeded with url: /v1/devices/2afd9022-b0c1-4ab0-be32-fd2c72870eb4/commands (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x68b02310>: Failed to establish a new connection: [Errno -3] Try again')

**Comment by jaruba** [comment]
Try setting `app_list` manually, and read this page carefully: https://github.com/jaruba/ha-samsungtv-tizen/blob/master/App_list.md

Try setting both the possible IDs for each app with the `/` between them.

**Comment by josiamichael** [comment]
I'm having similar issues and I have set the `app_list` manually, still same results.

**Comment by jaruba** [comment]
@fellipeisensee if it's still not working try the possible fix from this issue: https://github.com/jaruba/ha-samsungtv-tizen/issues/77

**Comment by jaruba** [comment]
@fellipeisensee What TV model, Tizen version do you have? Also what year was your TV fabricated in?

There is now a new issue about this: https://github.com/jaruba/ha-samsungtv-tizen/issues/82

I'd suggest moving the discussion there.
